apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: networkop/meshnet
  newTag: 8fe2da1-dirty
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: INTER_NODE_LINK_TYPE
        value: GRPC
  target:
    kind: DaemonSet
    name: meshnet
    namespace: meshnet
resources:
- ../../base/
