apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-meshnetd
  namespace: kube-system
  labels:
    k8s-app: meshnetd
spec:
  selector:
    matchLabels:
      name: kube-meshnetd
  template:
    metadata:
      labels:
        name: kube-meshnetd
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: meshnetd
        securityContext:
          privileged: true
        image: IMAGE_NAME
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 0
