apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
        # value: VXLAN
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: INTER_NODE_LINK_TYPE
        # value: VXLAN
        value: GRPC
  target:
    kind: DaemonSet
    name: meshnet
    namespace: meshnet
resources:
- ../../base/
images:
- name: networkop/meshnet
  newName: gcr.io/kt-nts-athena-dev/networkop/meshnet
  newTag: 1e6d7eb-dirty
