name: Release

on:
  push:
    


jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Install quemu emulators
        run: |
          docker run -it --rm --privileged tonistiigi/binfmt --install all
      - 
        name: Build and Push container images
        run: |
          make release